// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zhangphh_users/rpc/users/internal/logic"
	"zhangphh_users/rpc/users/internal/svc"
	"zhangphh_users/rpc/users/user"
)

type UserRPCServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRPCServiceServer
}

func NewUserRPCServiceServer(svcCtx *svc.ServiceContext) *UserRPCServiceServer {
	return &UserRPCServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRPCServiceServer) GetUserInfo(ctx context.Context, in *user.GetUserRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserRPCServiceServer) GetUserInfoByToken(ctx context.Context, in *user.GetUserByTokenRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserInfoByTokenLogic(ctx, s.svcCtx)
	return l.GetUserInfoByToken(in)
}
